"""
update_status.py - Regenerate status.md from live tasks.db state.

Run after any worker iteration to keep status.md current.
Usage: .venv/bin/python scripts/update_status.py [--project harness-v1]
"""
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DB_PATH = REPO_ROOT / "tasks.db"
PROJECTS_DIR = REPO_ROOT / "projects"


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_conn() -> sqlite3.Connection:
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def get_task_counts(conn: sqlite3.Connection) -> dict:
    row = conn.execute("""
        SELECT
            COUNT(*) FILTER (WHERE status='pending')  AS pending,
            COUNT(*) FILTER (WHERE status='locked')   AS locked,
            COUNT(*) FILTER (WHERE status='running')  AS running,
            COUNT(*) FILTER (WHERE status='done')     AS done,
            COUNT(*) FILTER (WHERE status='failed')   AS failed,
            COUNT(*) FILTER (WHERE status='blocked')  AS blocked
        FROM tasks
    """).fetchone()
    return dict(row)


def get_active_tasks(conn: sqlite3.Connection, limit: int = 5) -> list[dict]:
    rows = conn.execute("""
        SELECT id, status, priority, risk_level, description, updated_at
        FROM tasks
        WHERE status IN ('running', 'locked', 'pending')
        ORDER BY priority DESC, updated_at DESC
        LIMIT ?
    """, (limit,)).fetchall()
    return [dict(r) for r in rows]


def get_recent_done(conn: sqlite3.Connection, limit: int = 5) -> list[dict]:
    rows = conn.execute("""
        SELECT id, description, completed_at, evidence
        FROM tasks
        WHERE status = 'done'
        ORDER BY completed_at DESC
        LIMIT ?
    """, (limit,)).fetchall()
    return [dict(r) for r in rows]


def get_failed_tasks(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("""
        SELECT id, description, attempts, evidence
        FROM tasks
        WHERE status = 'failed'
        ORDER BY updated_at DESC
    """).fetchall()
    return [dict(r) for r in rows]


def get_cost_by_goal(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("""
        SELECT g.id, g.description, g.status, g.trust_level,
               COUNT(t.id) AS task_count,
               SUM(COALESCE(t.tokens_used, 0)) AS total_tokens,
               ROUND(SUM(COALESCE(t.cost_usd, 0)), 4) AS total_cost_usd
        FROM goals g
        LEFT JOIN tasks t ON t.goal_id = g.id
        GROUP BY g.id
        ORDER BY g.created_at DESC
        LIMIT 10
    """).fetchall()
    return [dict(r) for r in rows]


def render_status(conn: sqlite3.Connection, project: str) -> str:
    counts = get_task_counts(conn)
    active = get_active_tasks(conn)
    done = get_recent_done(conn)
    failed = get_failed_tasks(conn)
    costs = get_cost_by_goal(conn)

    lines = [
        f"# Status - {project}",
        f"\n**Updated:** {utcnow()[:19]}Z  (auto-generated by update_status.py)\n",
        "## Task Board\n",
        f"| Status | Count |",
        "|---|---|",
    ]
    for k, v in counts.items():
        lines.append(f"| {k} | {v} |")

    lines.append("\n## Active Tasks (top 5)\n")
    if active:
        lines.append("| ID | Status | Pri | Risk | Description |")
        lines.append("|---|---|---|---|---|")
        for t in active:
            lines.append(f"| {t['id'][:8]} | {t['status']} | {t['priority']} | {t['risk_level']} | {t['description'][:50]} |")
    else:
        lines.append("_No active tasks._")

    lines.append("\n## Recently Completed\n")
    if done:
        for t in done:
            lines.append(f"- `{t['id'][:8]}` {t['description'][:60]} ({(t['completed_at'] or '')[:10]})")
    else:
        lines.append("_None yet._")

    lines.append("\n## Failed Tasks (need triage)\n")
    if failed:
        for t in failed:
            lines.append(f"- `{t['id'][:8]}` {t['description'][:60]} (attempts: {t['attempts']})")
    else:
        lines.append("_None._")

    lines.append("\n## Cost by Goal (recent 10)\n")
    if costs:
        lines.append("| Goal | Trust | Tasks | Tokens | Cost USD |")
        lines.append("|---|---|---|---|---|")
        for g in costs:
            desc = g['description'][:45] if g['description'] else ''
            lines.append(
                f"| {desc} | {g['trust_level']} | {g['task_count']} "
                f"| {g['total_tokens'] or 0:,} | ${g['total_cost_usd'] or 0:.4f} |"
            )
    else:
        lines.append("_No goals yet._")

    return "\n".join(lines) + "\n"


def main():
    project = "harness-v1"
    if len(sys.argv) > 2 and sys.argv[1] == "--project":
        project = sys.argv[2]

    conn = get_conn()
    content = render_status(conn, project)

    status_path = PROJECTS_DIR / project / "status.md"
    status_path.parent.mkdir(parents=True, exist_ok=True)
    status_path.write_text(content)
    print(f"Updated: {status_path}")


if __name__ == "__main__":
    main()
